# CodeRabbit Configuration for Qdrant Loader
# This configures automated code reviews for pull requests

# Enable reviews for specific base branches
reviews:
  enabled: true
  # Review PRs targeting these branches:
  # - Any branch → develop
  # - develop → main
  # - hotfix/* → main
  # - hotfix/* → develop
  base_branches:
    - develop
    - main

# Review settings
review:
  enabled: true
  
  # Review all file types
  paths:
    - "**/*"
  
  # Exclude certain files from reviews
  exclude_paths:
    # Exclude markdown files (mostly documentation)
    - "**/*.md"
    # Exclude test files
    - "**/*.test.py"
    - "**/tests/**"

# Review behavior
behavior:
  # Review on PR open
  review_on_open: true
  # Review on new commits
  review_on_update: true
  # Review on comment (optional)
  review_on_comment: true

# Chat settings (for AI assistant features)
chat:
  enabled: true

# Summary settings
summary:
  # Enable PR summaries
  enabled: true
  # Include commit messages in summary
  include_commit_messages: true