FROM python:3.12-slim AS base

ENV PYTHONDONTWRITEBYTECODE=1

COPY --from=ghcr.io/astral-sh/uv:latest /uv /uvx /bin/

WORKDIR /qdrant-loader-mcp-server

COPY uv.lock pyproject.toml README.md* LICENSE* ./
COPY packages/qdrant-loader-core /qdrant-loader-mcp-server/packages/qdrant-loader-core
COPY packages/qdrant-loader-mcp-server /qdrant-loader-mcp-server/packages/qdrant-loader-mcp-server

RUN uv sync  --frozen --package qdrant-loader-mcp-server --package qdrant-loader-core --all-extras --no-dev --no-cache --no-install-project \
    && .venv/bin/python -m spacy download en_core_web_md

RUN find /qdrant-loader-mcp-server/.venv -name "*.a" -delete && \
    find /qdrant-loader-mcp-server/.venv -name "*.pyc" -delete && \
    find /qdrant-loader-mcp-server/.venv -name "__pycache__" -type d -exec rm -rf {} +



FROM python:3.12-slim

WORKDIR /qdrant-loader-mcp-server

ENV PYTHONUNBUFFERED=1
ENV PYTHONDONTWRITEBYTECODE=1


COPY --from=base /qdrant-loader-mcp-server/.venv /qdrant-loader-mcp-server/.venv
COPY packages/qdrant-loader-core /qdrant-loader-mcp-server/packages/qdrant-loader-core
COPY packages/qdrant-loader-mcp-server /qdrant-loader-mcp-server/packages/qdrant-loader-mcp-server

ENV PATH="/qdrant-loader-mcp-server/.venv/bin:$PATH"

CMD ["mcp-qdrant-loader", "--transport", "http", "--port", "8080", "--host", "0.0.0.0"]