# Template for sources configuration
# Copy this file to config.yaml and customize it for your needs
# Environment variables can be used with ${VARIABLE_NAME} syntax

# Global configuration for all sources
global:
  # Qdrant vector database configuration
  qdrant:
    url: "http://localhost:6333"
    api_key: null  # Optional API key for Qdrant Cloud
    collection_name: "documents"

  # Default chunking configuration
  # Controls how documents are split into chunks for processing
  chunking:
    chunk_size: 1500       # Maximum number of characters per chunk. Be careful not to set it too high to prevent token limits.
    chunk_overlap: 200      # Number of characters to overlap between chunks
  
  # Default embedding configuration
  # Controls how text is converted to vectors
  embedding:
    endpoint: "http://localhost:8080/v1" # Optionnal. Defines the endpoint to use for embedding. Defaults to OpenAI endpoint.
    model: "BAAI/bge-small-en-v1.5"  # Embedding model to use. Could be BAAI/bge-small-en-v1.5 (exemple for local use) or text-embedding-3-small (for OpenAI use)
    api_key: "${OPENAI_API_KEY}"     # API key for the embedding service (required for OpenAI models)
    batch_size: 100                  # Number of chunks to process in one batch
    vector_size: 384                # Optionnal. Vector size for the embedding model (384 for BAAI/bge-small-en-v1.5, 1536 for OpenAI models)
    tokenizer: "none"         # Optionnal. Tokenizer to use for token counting. Use 'cl100k_base' for OpenAI models or 'none' for other models.
    # Token limits (adjust based on your embedding model):
    # - OpenAI text-embedding-3-small/large: 8192 tokens max
    # - OpenAI text-embedding-ada-002: 8192 tokens max  
    # - BAAI/bge-small-en-v1.5: 512 tokens max
    # - sentence-transformers models: varies (typically 256-512)
    max_tokens_per_request: 8000     # Maximum total tokens per API request (leave buffer below model limit)
    max_tokens_per_chunk: 8000       # Maximum tokens per individual chunk (should match model's context limit)

  # State management configuration
  # Controls how document ingestion state is tracked
  state_management:
    database_path: "${STATE_DB_PATH}"  # Path to SQLite database file
    table_prefix: "qdrant_loader_"     # Prefix for database tables
    connection_pool:                   # Connection pool settings
      size: 5                         # Maximum number of connections
      timeout: 30                  # Connection timeout in seconds

  # File conversion configuration
  # Controls how non-text files (PDF, Office docs, etc.) are converted to text
  file_conversion:
    # Maximum file size for conversion (in bytes)
    max_file_size: 52428800  # 50MB
    
    # Timeout for conversion operations (in seconds)
    conversion_timeout: 300  # 5 minutes
    
    # MarkItDown specific settings
    markitdown:
      # Enable LLM integration for image descriptions
      enable_llm_descriptions: false
      # LLM model for image descriptions (when enabled)
      llm_model: "gpt-4o"
      # LLM endpoint (when enabled)
      llm_endpoint: "https://api.openai.com/v1"
      # API key for LLM service (required when enable_llm_descriptions is True)
      llm_api_key: "${OPENAI_API_KEY}"

# Source-specific configurations
# Each source type has its own configuration section
sources:
  # Public documentation sources (websites, documentation)
  publicdocs:
    # Example configuration for a documentation source
    my-docs:
      # Base URL of the documentation website
      base_url: "https://docs.example.com"
      
      # Specific version of the documentation to fetch
      version: "1.0"
      
      # Content type of the documentation
      content_type: "html"  # Options: html, markdown, etc.
      
      # Optional: Specific path pattern to match documentation pages
      # Uses glob syntax: ** matches any directory, * matches any file
      path_pattern: "/docs/{version}/**"
      
      # Optional: List of paths to exclude from processing
      exclude_paths:
        - "/docs/{version}/api-reference"
        - "/docs/{version}/changelog"
      
      # Optional: CSS selectors for content extraction
      # Helps identify and extract relevant content from HTML
      selectors:
        # Main content container selector
        content: "article.main-content"
        # Elements to remove (navigation, headers, footers)
        remove: 
          - "nav"
          - "header"
          - "footer"
          - ".sidebar"
        # Code blocks to preserve (will be kept in the content)
        code_blocks: "pre code"

      # File conversion settings for this source
      # Enable file conversion for this connector
      enable_file_conversion: true
      # Download and process attachments
      download_attachments: true

  # Git repository sources
  git:
    # Example configuration for a public repository
    public_repo:
      base_url: "https://github.com/example/repo.git"  # Repository URL
      branch: "main"                             # Branch to process
      include_paths:                             # Paths to include (glob patterns)
        - "docs/**"
        - "src/**"
        - "README.md"
      exclude_paths:                             # Paths to exclude (glob patterns)
        - "docs/archive/**"
        - "node_modules/**"
        - "venv/**"
      file_types:                                # File extensions to process
        - "*.md"
        - "*.rst"
        - "*.txt"
        - "*.py"
        - "*.js"
        - "*.ts"
        - "*.java"
        - "*.go"
        - "*.rb"
      max_file_size: 1048576                    # Maximum file size in bytes (1MB)
      depth: 1                                  # Maximum directory depth to process
      token: "${REPO_TOKEN}"                    #  GitHub Personal Access Token or none

      # File conversion settings for this source
      # Enable file conversion for this connector
      enable_file_conversion: true

    # Example configuration for a private GitHub repository
    private_github_repo:
      base_url: "${REPO_URL}"                        # Use environment variable
      branch: "main"
      token: "${REPO_TOKEN}"                    # GitHub Personal Access Token or none
      include_paths:
        - "docs/**"
      file_types:
        - "*.md"

      # File conversion settings for this source
      # Enable file conversion for this connector
      enable_file_conversion: true

  # Confluence documentation sources
  confluence:
    # Example configuration for Confluence Cloud
    my-cloud-space:
      base_url: "https://mycompany.atlassian.net/wiki"  # Confluence Cloud URL
      deployment_type: "cloud"                  # Deployment type: cloud, datacenter, or server
      space_key: "${CONFLUENCE_SPACE_KEY}"      # Space to process
      content_types:                            # Types of content to process
        - "page"
        - "blogpost"
      include_labels: []                        # Only process content with these labels
      exclude_labels: []                        # Skip content with these labels
      token: "${CONFLUENCE_TOKEN}"              # Confluence API token (from id.atlassian.com)
      email: "${CONFLUENCE_EMAIL}"              # Confluence user email

      # File conversion settings for this source
      # Enable file conversion for this connector
      enable_file_conversion: true
      # Download and process attachments
      download_attachments: true

    # Example configuration for Confluence Data Center with Personal Access Token
    my-datacenter-space-pat:
      base_url: "https://confluence.mycompany.com"  # Confluence Data Center URL
      deployment_type: "datacenter"             # Deployment type: cloud, datacenter, or server
      space_key: "${CONFLUENCE_SPACE_KEY}"      # Space to process
      content_types:                            # Types of content to process
        - "page"
        - "blogpost"
      include_labels: []                        # Only process content with these labels
      exclude_labels: []                        # Skip content with these labels
      token: "${CONFLUENCE_PAT}"                # Personal Access Token (generated in Confluence)

      # File conversion settings for this source
      # Enable file conversion for this connector
      enable_file_conversion: true
      # Download and process attachments
      download_attachments: true



  # JIRA issue tracking sources
  jira:
    # Example configuration for Jira Cloud
    my-cloud-project:
      base_url: "https://mycompany.atlassian.net"  # Jira Cloud URL
      deployment_type: "cloud"                  # Deployment type: cloud, datacenter, or server
      project_key: "${JIRA_PROJECT_KEY}"        # Project to process
      requests_per_minute: 60                   # Rate limit for API calls
      page_size: 50                            # Number of issues per API request
      process_attachments: true                 # Whether to process issue attachments
      track_last_sync: true                    # Track last sync time for incremental updates
      token: "${JIRA_TOKEN}"                    # Jira API token (from id.atlassian.com)
      email: "${JIRA_EMAIL}"                    # Jira user email

      # File conversion settings for this source
      # Enable file conversion for this connector
      enable_file_conversion: true
      # Download and process attachments
      download_attachments: true

    # Example configuration for Jira Data Center with Personal Access Token
    my-datacenter-project:
      base_url: "https://jira.mycompany.com"    # Jira Data Center URL
      deployment_type: "datacenter"             # Deployment type: cloud, datacenter, or server
      project_key: "${JIRA_PROJECT_KEY}"        # Project to process
      requests_per_minute: 60                   # Rate limit for API calls
      page_size: 50                            # Number of issues per API request
      process_attachments: true                 # Whether to process issue attachments
      track_last_sync: true                    # Track last sync time for incremental updates
      token: "${JIRA_PAT}"                      # Personal Access Token (generated in Jira)

      # File conversion settings for this source
      # Enable file conversion for this connector
      enable_file_conversion: true
      # Download and process attachments
      download_attachments: true

  # Local file sources
  localfile:
    # Example configuration for a local file source
    my-local-files:
      base_url: "file:///path/to/local/files"  # Base directory to scan
      include_paths:
        - "docs/**"
        - "README.md"
      exclude_paths:
        - "docs/archive/**"
        - "tmp/**"
      file_types:
        - "*.md"
        - "*.txt"
        - "*.py"
        - "*.json"
        - "*.yaml"
      max_file_size: 1048576  # Maximum file size in bytes (1MB)

      # File conversion settings for this source
      # Enable file conversion for this connector
      enable_file_conversion: true